---
# Eugene's overrides to mac-dev-playbook

configure_dotfiles: no
configure_sudoers: yes
configure_terminal: no
configure_osx: no

# Homebrew
homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_installed_packages:
  - coreutils
  - git
  - wget
  - { name: gnu-tar, install_options: "with-default-names" }                  # GNU tar is needed for ansible unarchive tasks
  - gradle
  - groovysdk
  - maven@3.3
  - packer
  - python3
  - terraform
  - minikube

homebrew_linked_packages:
  - python3

homebrew_cask_apps:
  - adobe-acrobat-reader
  - docker
  - dropbox
  - evernote
  - google-chrome
  - intellij-idea
  - java
  - java8
  - jollysfastvnc
  - parallels-desktop
  - perforce
  - p4v
  - slack
  - spotify
  - vagrant
  - virtualbox