---
- name: Create /usr/local/Frameworks
  file:
    path: "/usr/local/Frameworks"
    owner: "{{ ansible_user_id }}"
    group: "admin"
    state: directory
  become: true

- name: Ensure configured homebrew packages are linked
  shell: "brew link {{ item.name | default(item) }}"
  with_items: "{{ homebrew_linked_packages }}"
  register: brew_link
  changed_when: not (brew_link.stderr is search("Already linked"))

- name: Create a symbolic links for openssl python fix
  file:
    src: "/usr/local/opt/openssl/lib/{{ item }}"
    dest: "/usr/local/lib/{{ item }}"
    owner: "root"
    group: "admin"
    state: link
  become: true
  with_items:
    - libssl.dylib
    - libcrypto.dylib

- name: Create docker l0 alias script
  template:
    src: docker-host-alias.sh.j2
    dest: "/usr/local/bin/docker-host-alias.sh"
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "admin"
  become: true

- name: Run docker l0 alias script on startup
  template:
    src: docker-host-alias.plist.j2
    dest: "/Library/LaunchAgents/docker-host-alias.plist"
    owner: "{{ ansible_user_id }}"
    group: "admin"
  become: true

- name: Set zsh as default shell
  user: name={{ ansible_user_id }} shell=/usr/local/bin/zsh
  become: true

- name: Update npm to latest
  shell: "npm install -g npm"

- name: Install nvm
  git:
    repo: "https://github.com/nvm-sh/nvm.git"
    version: "{{ nvm_version }}"
    dest: "~/.nvm"
  tags:
    - node

- name: Install node versions
  shell: ". ~/.nvm/nvm.sh; nvm install {{ item }} --latest-npm"
  with_items:
    - "node"
    - "--lts=carbon"
    - "--lts=dubnium"
    - "--lts=erbium"
  tags:
    - node

- name: Set node default
  shell: ". ~/.nvm/nvm.sh; nvm alias default lts/erbium"

- name: Add git package URL to ~/.npmrc
  lineinfile:
    dest: "~/.npmrc"
    state: present
    line: '@gone-skiing:registry=https://npm.pkg.github.com/'
  tags:
    - node

- name: Add git package token to ~/.npmrc
  lineinfile:
    dest: "~/.npmrc"
    state: present
    regexp: '^//npm.pkg.github.com/:_authToken='
    line: '//npm.pkg.github.com/:_authToken={{ git_package_token }}'
  tags:
    - node
