---
- name: Create /usr/local/Frameworks
  file:
    path: "/usr/local/Frameworks"
    owner: "{{ ansible_user_id }}"
    group: "admin"
    state: directory
  become: true

- name: Ensure configured homebrew packages are linked
  shell: "brew link {{ item.name | default(item) }}"
  with_items: "{{ homebrew_linked_packages }}"
  register: brew_link
  changed_when: not (brew_link.stderr is search("Already linked"))

# - name: Install pip packages
#   pip:
#     name: git-pull-request
#     virtualenv: ~/python_env
#     virtualenv_command: /usr/local/bin/pyvenv

- name: Create docker l0 alias script
  template:
    src: docker-host-alias.sh.j2
    dest: "/usr/local/bin/docker-host-alias.sh"
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "admin"
  become: true

- name: Run docker l0 alias script on startup
  template:
    src: docker-host-alias.plist.j2
    dest: "/Library/LaunchAgents/docker-host-alias.plist"
    owner: "{{ ansible_user_id }}"
    group: "admin"
  become: true

- name: Set zsh as default shell
  user: name={{ ansible_user_id }} shell=/usr/local/bin/zsh
  become: true

- name: Install nvm
  git:
    repo: "https://github.com/nvm-sh/nvm.git"
    version: "{{ nvm_version }}"
    dest: "~/.nvm"
  tags:
    - node

- name: Install node versions
  shell: ". ~/.nvm/nvm.sh; nvm install {{ item }} --latest-npm"
  with_items:
    - "node"
    - "--lts=carbon"
    - "--lts=dubnium"
  tags:
    - node