---
- name: Make sure wheel group is present
  group: name=wheel state=present
  become: true
  tags:
    - setup-user

- name: Make sure wheel has passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - setup-user

- name: Add user in wheel group
  become: true
  user: 
    name: '{{ansible_user_id}}'
    groups: 
      - wheel
    append: yes
    state: present
  tags:
    - setup-user

- name: Add user in wheel group
  become: true
  user:
    name: '{{ansible_user_id}}'
    shell: /usr/local/bin/zsh
  tags:
    - setup-user
    - setup-zsh

- name: Replace resource files
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
  tags:
    - setup-user
    - setup-zsh
  with_items:
    - zshrc
    - zshrc.local
    - zshrc.java
    - gitconfig
    - gitignore_global
    - netrc

- name: Include zsh setup
  include_tasks: setup-zsh.yml
  tags:
    - setup-zsh

- name: Create default ~/.m2/settings.xml
  template:
    src: "settings-external.xml.j2"
    dest: "~/.m2/settings.xml"
  tags:
    - setup-user

- name: Copy config to mac-dev-playbook
  template:
    src: config.j2
    dest: "~/dev/mac-dev-playbook/config.yml"
  tags:
    - setup-user

- name: Make sure wheel has passwordless sudo in mac-dev-playbook
  lineinfile:
    dest: "~/dev/mac-dev-playbook/templates/sudoers.j2"
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - setup-user
