---

- name: Replace .zshrc_user_extensions
  template:
    src: zshrc_user_extensions.j2
    dest: "~/.zshrc_user_extensions"
  tags:
  - setup-user

- name: Create .netrc file
  template:
    src: netrc.j2
    dest: "~/.netrc"
  tags:
  - setup-user

- name: Create ~/.config
  file:
    path: "~/.config"
    state: directory

- name: Create ~/.config/terminator
  file:
    path: "~/.config/terminator"
    state: directory

- name: Create terminator config file
  template:
    src: terminator-config.j2
    dest: "~/.config/terminator/config"
  tags:
  - setup-user