---

- name: Clone github repositories
  git:
    repo: "https://github.com/{{ item.owner }}/{{ item.repo }}.git"
    version: master
    dest: "~/dev/{{ item.repo }}"
    accept_hostkey: yes
    update: no
  with_items:
    - { owner: gone-skiing,  repo: mac-dev-playbook }
    - { owner: gone-skiing,  repo: react-sample-app }
    - { owner: gone-skiing,  repo: react-course }
    - { owner: spring-cloud, repo: spring-cloud-dataflow-server-kubernetes }
    - { owner: wurstmeister, repo: kafka-docker }
    - { owner: ansible, repo: ansible }
    - { owner: gone-skiing, repo: ansible-role-jenkins }
    - { owner: geerlingguy, repo: ansible-role-nodejs }
    - { owner: geerlingguy, repo: ansible-role-docker }
    - { owner: foundery-rmb, repo: kubernetes-service-discovery }
    - { owner: bijukunjummen, repo: sample-spring-kafka-producer-consumer }
    - { owner: cer, repo: event-sourcing-examples }
    - { owner: sdaschner, repo: scalable-coffee-shop }
    - { owner: strimzi, repo: strimzi }
    - { owner: gone-skiing,                   repo: eventuateio-docker-networking-diagnostics }
    - { owner: eventuate-local-docker-images, repo: eventuate-local-docker-images }
  tags:
    - github